// Sample restaurant data with working image URLs
const restaurantData = [
  {
    id: 1,
    name: "Italian Delights",
    cuisine: "Italian",
    rating: 4.5,
    promoted: true,
    deliveryTime: "30-40 mins",
    address: "123 Pasta Lane, City",
    image:
      "https://images.pexels.com/photos/18032206/pexels-photo-18032206/free-photo-of-choice-of-delicious-food.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    menu: [
      {
        name: "Margherita Pizza",
        price: 510,
        category: "Mains",
        img: "https://images.pexels.com/photos/16890470/pexels-photo-16890470/free-photo-of-pizza-on-a-wooden-table.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Lasagna",
        price: 380,
        category: "Mains",
        img: "https://images.pexels.com/photos/4079520/pexels-photo-4079520.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Bruschetta",
        price: 400,
        category: "Starters",
        img: "https://images.pexels.com/photos/29021173/pexels-photo-29021173/free-photo-of-delicious-italian-pizza-with-basil-at-restaurant.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Garlic Bread",
        price: 250,
        category: "Sides",
        img: "https://images.pexels.com/photos/1718446/pexels-photo-1718446.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Tiramisu",
        price: 650,
        category: "Desserts",
        img: "https://images.pexels.com/photos/18955555/pexels-photo-18955555/free-photo-of-variety-of-desserts-in-glass-cups.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Panna Cotta",
        price: 310,
        category: "Desserts",
        img: "https://images.pexels.com/photos/15735976/pexels-photo-15735976/free-photo-of-cake-on-plate.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Espresso",
        price: 275,
        category: "Beverages",
        img: "https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Cappuccino",
        price: 335,
        category: "Beverages",
        img: "https://images.pexels.com/photos/302896/pexels-photo-302896.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Red Wine",
        price: 345,
        category: "Beverages",
        img: "https://images.pexels.com/photos/2702805/pexels-photo-2702805.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "White Wine",
        price: 275,
        category: "Beverages",
        img: "https://images.pexels.com/photos/1123260/pexels-photo-1123260.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
    ],
  },
  {
    id: 2,
    name: "Sushi Zen",
    cuisine: "Japanese",
    rating: 4.7,
    promoted: false,
    deliveryTime: "20-30 mins",
    address: "456 Sushi St, City",
    image:
      "https://images.pexels.com/photos/670702/pexels-photo-670702.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    menu: [
      {
        name: "Sushi Roll",
        price: 425,
        category: "Mains",
        img: "https://images.pexels.com/photos/11661144/pexels-photo-11661144.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Sashimi",
        price: 352,
        category: "Mains",
        img: "https://images.pexels.com/photos/2871756/pexels-photo-2871756.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Miso Soup",
        price: 300,
        category: "Starters",
        img: "https://images.pexels.com/photos/18469419/pexels-photo-18469419/free-photo-of-homemade-ramen-with-egg-and-salmon.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Edamame",
        price: 450,
        category: "Starters",
        img: "https://images.pexels.com/photos/3297367/pexels-photo-3297367.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Tempura",
        price: 465,
        category: "Sides",
        img: "https://images.pexels.com/photos/17592736/pexels-photo-17592736/free-photo-of-food-on-table.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Rice",
        price: 150,
        category: "Sides",
        img: "https://images.pexels.com/photos/674574/pexels-photo-674574.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Green Tea",
        price: 100,
        category: "Beverages",
        img: "https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Sake",
        price: 150,
        category: "Beverages",
        img: "https://images.pexels.com/photos/18510255/pexels-photo-18510255/free-photo-of-a-drink-in-a-glass-bottle-and-small-cups-on-the-bar-counter.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Matcha Ice Cream",
        price: 250,
        category: "Desserts",
        img: "https://images.pexels.com/photos/28309088/pexels-photo-28309088/free-photo-of-ice-cream-cones-with-nuts-and-chocolate-on-a-wooden-table.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Mochi",
        price: 200,
        category: "Desserts",
        img: "https://images.pexels.com/photos/17655857/pexels-photo-17655857/free-photo-of-colorful-mochi-dessert-in-box.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
    ],
  },
  {
    id: 3,
    name: "Burger Haven",
    cuisine: "American",
    rating: 4.3,
    promoted: false,
    deliveryTime: "25-35 mins",
    address: "789 Burger Blvd, City",
    image:
      "https://images.pexels.com/photos/2983101/pexels-photo-2983101.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    menu: [
      {
        name: "Chicken Wings",
        price: 350,
        category: "Starters",
        img: "https://images.pexels.com/photos/1059943/pexels-photo-1059943.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Classic Cheeseburger",
        price: 375,
        category: "Mains",
        img: "https://images.pexels.com/photos/28828553/pexels-photo-28828553/free-photo-of-gourmet-cheeseburger-with-crispy-bacon-and-fresh-ingredients.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Bacon Burger",
        price: 385,
        category: "Mains",
        img: "https://images.pexels.com/photos/19345991/pexels-photo-19345991/free-photo-of-delicious-beef-burger.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Veggie Burger",
        price: 320,
        category: "Mains",
        img: "https://images.pexels.com/photos/1431305/pexels-photo-1431305.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Sweet Potato Fries",
        price: 250,
        category: "Sides",
        img: "https://images.pexels.com/photos/1893555/pexels-photo-1893555.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Onion Rings",
        price: 180,
        category: "Sides",
        img: "https://images.pexels.com/photos/263049/pexels-photo-263049.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Milkshake",
        price: 200,
        category: "Desserts",
        img: "https://images.pexels.com/photos/103566/pexels-photo-103566.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Ice Cream Sundae",
        price: 275,
        category: "Desserts",
        img: "https://images.pexels.com/photos/1362534/pexels-photo-1362534.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Cola",
        price: 100,
        category: "Beverages",
        img: "https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Iced Tea",
        price: 80,
        category: "Beverages",
        img: "https://images.pexels.com/photos/1484678/pexels-photo-1484678.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
    ],
  },
  {
    id: 4,
    name: "Indian Spice",
    cuisine: "Indian",
    rating: 4.6,
    promoted: true,
    deliveryTime: "30-45 mins",
    address: "321 Curry Rd, City",
    image:
      "https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    menu: [
      {
        name: "Butter Chicken",
        price: 275,
        category: "Mains",
        img: "https://images.pexels.com/photos/12737809/pexels-photo-12737809.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Chicken Tikka",
        price: 300,
        category: "Mains",
        img: "https://images.pexels.com/photos/12312104/pexels-photo-12312104.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Paneer Butter Masala",
        price: 325,
        category: "Mains",
        img: "https://images.pexels.com/photos/11115801/pexels-photo-11115801.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Samosas",
        price: 100,
        category: "Starters",
        img: "https://images.pexels.com/photos/4449068/pexels-photo-4449068.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Aloo Tikki",
        price: 125,
        category: "Starters",
        img: "https://images.pexels.com/photos/8617361/pexels-photo-8617361.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Naan",
        price: 35,
        category: "Sides",
        img: "https://images.pexels.com/photos/28674556/pexels-photo-28674556/free-photo-of-assorted-indian-breads-in-a-wicker-basket.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Biryani",
        price: 350,
        category: "Mains",
        img: "https://images.pexels.com/photos/17696653/pexels-photo-17696653/free-photo-of-chicken-wings-in-rice-with-saffron.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Mango Lassi",
        price: 150,
        category: "Beverages",
        img: "https://images.pexels.com/photos/26842849/pexels-photo-26842849/free-photo-of-mango-slices-with-syrup-in-cup.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Chai Tea",
        price: 50,
        category: "Beverages",
        img: "https://images.pexels.com/photos/9452278/pexels-photo-9452278.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Gulab Jamun",
        price: 125,
        category: "Desserts",
        img: "https://images.pexels.com/photos/7449105/pexels-photo-7449105.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
    ],
  },
  {
    id: 5,
    name: "Taco Fiesta",
    cuisine: "Mexican",
    rating: 4.4,
    promoted: true,
    deliveryTime: "20-25 mins",
    image:
      "https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg?auto=compress&cs=tinysrgb&w=600",
    address: "456 Taco St, City",
    menu: [
      {
        name: "Chicken Tacos",
        price: 275,
        category: "Tacos",
        img: "https://images.pexels.com/photos/4958529/pexels-photo-4958529.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Beef Tacos",
        price: 475,
        category: "Tacos",
        img: "https://images.pexels.com/photos/7613555/pexels-photo-7613555.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Fish Tacos",
        price: 250,
        category: "Tacos",
        img: "https://images.pexels.com/photos/8448318/pexels-photo-8448318.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Vegetarian Tacos",
        price: 200,
        category: "Tacos",
        img: "https://images.pexels.com/photos/4958522/pexels-photo-4958522.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Carnitas Tacos",
        price: 350,
        category: "Tacos",
        img: "https://images.pexels.com/photos/7772198/pexels-photo-7772198.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Beef Burrito",
        price: 475,
        category: "Burritos",
        img: "https://images.pexels.com/photos/14979836/pexels-photo-14979836/free-photo-of-burrito-in-close-up-photography.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Chicken Burrito",
        price: 310,
        category: "Burritos",
        img: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Guacamole",
        price: 175,
        category: "Sides",
        img: "https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Churros",
        price: 100,
        category: "Desserts",
        img: "https://images.pexels.com/photos/5255957/pexels-photo-5255957.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Salsa",
        price: 125,
        category: "Sides",
        img: "https://images.pexels.com/photos/2641886/pexels-photo-2641886.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
    ],
  },
  {
    id: 6,
    name: "Pizza Palace",
    cuisine: "Italian",
    rating: 4.8,
    promoted: true,
    deliveryTime: "30-40 mins",
    image:
      "https://images.pexels.com/photos/708587/pexels-photo-708587.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    address: "123 Pizza Rd, City",
    menu: [
      {
        name: "Pepperoni Pizza",
        price: 345,
        category: "Mains",
        img: "https://images.pexels.com/photos/708587/pexels-photo-708587.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Margherita Pizza",
        price: 375,
        category: "Mains",
        img: "https://images.pexels.com/photos/11397866/pexels-photo-11397866.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "BBQ Chicken Pizza",
        price: 410,
        category: "Mains",
        img: "https://images.pexels.com/photos/1732805/pexels-photo-1732805.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Garlic Bread",
        price: 125,
        category: "Sides",
        img: "https://images.pexels.com/photos/959926/pexels-photo-959926.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Pasta Carbonara",
        price: 315,
        category: "Mains",
        img: "https://images.pexels.com/photos/1125374/pexels-photo-1125374.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Caesar Salad",
        price: 135,
        category: "Salads",
        img: "https://images.pexels.com/photos/1606619/pexels-photo-1606619.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Panna Cotta",
        price: 75,
        category: "Desserts",
        img: "https://images.pexels.com/photos/11397866/pexels-photo-11397866.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Lasagna",
        price: 410,
        category: "Mains",
        img: "https://images.pexels.com/photos/1586071/pexels-photo-1586071.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Focaccia",
        price: 210,
        category: "Sides",
        img: "https://images.pexels.com/photos/3737066/pexels-photo-3737066.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Tiramisu",
        price: 145,
        category: "Desserts",
        img: "https://images.pexels.com/photos/1051373/pexels-photo-1051373.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
    ],
  },
  {
    id: 7,
    name: "Indian Spice",
    cuisine: "Indian",
    rating: 4.9,
    promoted: false,
    deliveryTime: "35-45 mins",
    image:
      "https://images.pexels.com/photos/941869/pexels-photo-941869.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    address: "789 Spice St, City",
    menu: [
      {
        name: "Butter Chicken",
        price: 450,
        category: "Mains",
        img: "https://images.pexels.com/photos/2340958/pexels-photo-2340958.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Chicken Biryani",
        price: 350,
        category: "Mains",
        img: "https://images.pexels.com/photos/1037370/pexels-photo-1037370.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Vegetable Samosa",
        price: 75,
        category: "Appetizers",
        img: "https://images.pexels.com/photos/4140319/pexels-photo-4140319.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Palak Paneer",
        price: 310,
        category: "Mains",
        img: "https://images.pexels.com/photos/1059967/pexels-photo-1059967.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Chole Bhature",
        price: 325,
        category: "Mains",
        img: "https://images.pexels.com/photos/3739918/pexels-photo-3739918.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Aloo Gobi",
        price: 275,
        category: "Mains",
        img: "https://images.pexels.com/photos/3745103/pexels-photo-3745103.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Gulab Jamun",
        price: 125,
        category: "Desserts",
        img: "https://images.pexels.com/photos/7449105/pexels-photo-7449105.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Naan",
        price: 50,
        category: "Sides",
        img: "https://images.pexels.com/photos/1746739/pexels-photo-1746739.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Raita",
        price: 75,
        category: "Sides",
        img: "https://images.pexels.com/photos/4157356/pexels-photo-4157356.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Lassi",
        price: 100,
        category: "Drinks",
        img: "https://images.pexels.com/photos/1313797/pexels-photo-1313797.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
    ],
  },
  {
    id: 8,
    name: "Healthy Greens",
    cuisine: "Vegetarian",
    rating: 4.2,
    promoted: false,
    deliveryTime: "25-30 mins",
    image:
      "https://images.pexels.com/photos/5900506/pexels-photo-5900506.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    address: "456 Greenway Dr, City",
    menu: [
      {
        name: "Quinoa Salad",
        price: 100,
        category: "Salads",
        img: "https://images.pexels.com/photos/248509/pexels-photo-248509.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Avocado Toast",
        price: 200,
        category: "Breakfast",
        img: "https://images.pexels.com/photos/1351238/pexels-photo-1351238.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Vegan Brownie",
        price: 175,
        category: "Desserts",
        img: "https://images.pexels.com/photos/29173451/pexels-photo-29173451/free-photo-of-refreshing-acai-bowl-with-fresh-kiwi-and-strawberry.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Vegan Pancakes",
        price: 255,
        category: "Breakfast",
        img: "https://images.pexels.com/photos/2710284/pexels-photo-2710284.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Stuffed Avocados",
        price: 125,
        category: "Appetizers",
        img: "https://images.pexels.com/photos/1861219/pexels-photo-1861219.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Vegan Wrap",
        price: 195,
        category: "Wraps",
        img: "https://images.pexels.com/photos/3596517/pexels-photo-3596517.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Chickpea Salad",
        price: 275,
        category: "Salads",
        img: "https://images.pexels.com/photos/2046786/pexels-photo-2046786.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Sweet Potato Fries",
        price: 155,
        category: "Sides",
        img: "https://images.pexels.com/photos/1056466/pexels-photo-1056466.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Lentil Soup",
        price: 195,
        category: "Soups",
        img: "https://images.pexels.com/photos/4137783/pexels-photo-4137783.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Fruit Smoothie",
        price: 110,
        category: "Drinks",
        img: "https://images.pexels.com/photos/1500192/pexels-photo-1500192.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
    ],
  },
  {
    id: 9,
    name: "BBQ Haven",
    cuisine: "Barbecue",
    rating: 4.5,
    promoted: false,
    deliveryTime: "40-50 mins",
    image:
      "https://images.pexels.com/photos/2233729/pexels-photo-2233729.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    address: "123 Grill St, City",
    menu: [
      {
        name: "BBQ Ribs",
        price: 357,
        category: "Mains",
        img: "https://images.pexels.com/photos/27953851/pexels-photo-27953851/free-photo-of-juicy-chicken-meat.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Pulled Pork Sandwich",
        price: 155,
        category: "Sandwiches",
        img: "https://images.pexels.com/photos/5981144/pexels-photo-5981144.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Mac and Cheese",
        price: 210,
        category: "Sides",
        img: "https://images.pexels.com/photos/5107162/pexels-photo-5107162.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Grilled Chicken",
        price: 395,
        category: "Mains",
        img: "https://images.pexels.com/photos/3861482/pexels-photo-3861482.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "BBQ Sausages",
        price: 455,
        category: "Mains",
        img: "https://images.pexels.com/photos/4128290/pexels-photo-4128290.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Corn on the Cob",
        price: 220,
        category: "Sides",
        img: "https://images.pexels.com/photos/1021043/pexels-photo-1021043.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Grilled Veggies",
        price: 155,
        category: "Sides",
        img: "https://images.pexels.com/photos/4870466/pexels-photo-4870466.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "BBQ Chicken Wings",
        price: 275,
        category: "Appetizers",
        img: "https://images.pexels.com/photos/4632285/pexels-photo-4632285.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Coleslaw",
        price: 125,
        category: "Sides",
        img: "https://images.pexels.com/photos/2700341/pexels-photo-2700341.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Lemonade",
        price: 100,
        category: "Drinks",
        img: "https://images.pexels.com/photos/2846491/pexels-photo-2846491.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
    ],
  },
  {
    id: 10,
    name: "Greek Delights",
    cuisine: "Greek",
    rating: 4.6,
    promoted: true,
    deliveryTime: "30-35 mins",
    image:
      "https://images.pexels.com/photos/29149761/pexels-photo-29149761/free-photo-of-gourmet-grilled-fish-with-colorful-vegetables.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    address: "456 Greek Rd, City",
    menu: [
      {
        name: "Gyro Wrap",
        price: 165,
        category: "Wraps",
        img: "https://images.pexels.com/photos/11286814/pexels-photo-11286814.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Greek Salad",
        price: 125,
        category: "Salads",
        img: "https://images.pexels.com/photos/1211887/pexels-photo-1211887.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Baklava",
        price: 75,
        category: "Desserts",
        img: "https://images.pexels.com/photos/7317605/pexels-photo-7317605.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Souvlaki",
        price: 405,
        category: "Mains",
        img: "https://images.pexels.com/photos/1062628/pexels-photo-1062628.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Moussaka",
        price: 335,
        category: "Mains",
        img: "https://images.pexels.com/photos/4741063/pexels-photo-4741063.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Hummus with Pita",
        price: 175,
        category: "Appetizers",
        img: "https://images.pexels.com/photos/1628107/pexels-photo-1628107.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Tzatziki Dip",
        price: 195,
        category: "Appetizers",
        img: "https://images.pexels.com/photos/5188883/pexels-photo-5188883.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Feta Cheese",
        price: 225,
        category: "Sides",
        img: "https://images.pexels.com/photos/4430264/pexels-photo-4430264.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Spanakopita",
        price: 750,
        category: "Mains",
        img: "https://images.pexels.com/photos/1255678/pexels-photo-1255678.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Greek Coffee",
        price: 175,
        category: "Drinks",
        img: "https://images.pexels.com/photos/1054098/pexels-photo-1054098.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
    ],
  },
  {
    id: 11,
    name: "Seafood Paradise",
    cuisine: "Seafood",
    rating: 4.7,
    promoted: false,
    deliveryTime: "25-35 mins",
    image:
      "https://images.pexels.com/photos/2689419/pexels-photo-2689419.jpeg?auto=compress&cs=tinysrgb&w=600",
    address: "123 Ocean St, City",
    menu: [
      {
        name: "Grilled Salmon",
        price: 425,
        category: "Mains",
        img: "https://images.pexels.com/photos/29149763/pexels-photo-29149763/free-photo-of-grilled-salmon-with-fresh-salad-on-black-plate.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Fish Tacos",
        price: 395,
        category: "Mains",
        img: "https://images.pexels.com/photos/8448322/pexels-photo-8448322.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Lobster Roll",
        price: 355,
        category: "Mains",
        img: "https://images.pexels.com/photos/12318086/pexels-photo-12318086.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Shrimp Cocktail",
        price: 155,
        category: "Appetizers",
        img: "https://images.pexels.com/photos/1761290/pexels-photo-1761290.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Clam Chowder",
        price: 175,
        category: "Soup",
        img: "https://images.pexels.com/photos/3112739/pexels-photo-3112739.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Crab Cakes",
        price: 225,
        category: "Mains",
        img: "https://images.pexels.com/photos/2975865/pexels-photo-2975865.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Seafood Paella",
        price: 425,
        category: "Mains",
        img: "https://images.pexels.com/photos/1182864/pexels-photo-1182864.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Seaweed Salad",
        price: 125,
        category: "Salads",
        img: "https://images.pexels.com/photos/1761036/pexels-photo-1761036.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Fish and Chips",
        price: 410,
        category: "Mains",
        img: "https://images.pexels.com/photos/1021010/pexels-photo-1021010.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Grilled Scallops",
        price: 375,
        category: "Mains",
        img: "https://images.pexels.com/photos/3060807/pexels-photo-3060807.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
    ],
  },
  {
    id: 12,
    name: "Taste of India",
    cuisine: "Indian",
    rating: 4.8,
    promoted: false,
    deliveryTime: "30-40 mins",
    image:
      "https://images.pexels.com/photos/7182077/pexels-photo-7182077.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    address: "456 Spice Rd, City",
    menu: [
      {
        name: "Chicken Tikka",
        price: 275,
        category: "Mains",
        img: "https://images.pexels.com/photos/20702403/pexels-photo-20702403/free-photo-of-meat-on-plates-with-onion-and-lime-slices.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Paneer Masala",
        price: 375,
        category: "Mains",
        img: "https://images.pexels.com/photos/20408461/pexels-photo-20408461/free-photo-of-photo-of-a-curry-dish-served-in-a-pan-and-bowls-with-spices.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Ras Malai",
        price: 200,
        category: "Dessert",
        img: "https://media.istockphoto.com/id/515853026/photo/traditional-rasmalai-or-ras-malai-indian-dessert-bengali-sweet.jpg?s=1024x1024&w=is&k=20&c=gSOKfjR5dKCrePmLwfhFLDkCpYIL6QjlzUM7jo113ZA=",
      },
      {
        name: "Butter Chicken",
        price: 450,
        category: "Mains",
        img: "https://images.pexels.com/photos/1033424/pexels-photo-1033424.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Samosa",
        price: 175,
        category: "Appetizers",
        img: "https://images.pexels.com/photos/1403061/pexels-photo-1403061.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Aloo Gobi",
        price: 200,
        category: "Mains",
        img: "https://images.pexels.com/photos/4576368/pexels-photo-4576368.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Naan Bread",
        price: 50,
        category: "Bread",
        img: "https://images.pexels.com/photos/1068538/pexels-photo-1068538.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Chole Bhature",
        price: 255,
        category: "Mains",
        img: "https://images.pexels.com/photos/1069843/pexels-photo-1069843.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Lassi",
        price: 155,
        category: "Drinks",
        img: "https://images.pexels.com/photos/1019051/pexels-photo-1019051.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Gulab Jamun",
        price: 150,
        category: "Dessert",
        img: "https://images.pexels.com/photos/1069859/pexels-photo-1069859.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
    ],
  },
  {
    id: 13,
    name: "Veggie Delight",
    cuisine: "Vegetarian",
    rating: 4.3,
    promoted: false,
    deliveryTime: "20-25 mins",
    image:
      "https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    address: "123 Green St, City",
    menu: [
      {
        name: "Vegan Burger",
        price: 275,
        category: "Mains",
        img: "https://images.pexels.com/photos/1624473/pexels-photo-1624473.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Stuffed Bell Peppers",
        price: 375,
        category: "Mains",
        img: "https://images.pexels.com/photos/1633495/pexels-photo-1633495.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Tofu Salad",
        price: 150,
        category: "Salads",
        img: "https://images.pexels.com/photos/1211887/pexels-photo-1211887.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Vegan Pizza",
        price: 350,
        category: "Mains",
        img: "https://images.pexels.com/photos/1050131/pexels-photo-1050131.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Vegetable Stir Fry",
        price: 410,
        category: "Mains",
        img: "https://images.pexels.com/photos/4549001/pexels-photo-4549001.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Zucchini Noodles",
        price: 350,
        category: "Mains",
        img: "https://images.pexels.com/photos/4163267/pexels-photo-4163267.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Mango Smoothie",
        price: 140,
        category: "Drinks",
        img: "https://images.pexels.com/photos/1345474/pexels-photo-1345474.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Chickpea Hummus",
        price: 100,
        category: "Appetizers",
        img: "https://images.pexels.com/photos/3201344/pexels-photo-3201344.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Cauliflower Wings",
        price: 160,
        category: "Appetizers",
        img: "https://images.pexels.com/photos/4105565/pexels-photo-4105565.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Acai Bowl",
        price: 80,
        category: "Dessert",
        img: "https://images.pexels.com/photos/1125074/pexels-photo-1125074.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
    ],
  },
  {
    id: 14,
    name: "Dim Sum House",
    cuisine: "Chinese",
    rating: 4.5,
    promoted: false,
    deliveryTime: "25-30 mins",
    image:
      "https://images.pexels.com/photos/5409020/pexels-photo-5409020.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    address: "456 Dim Sum Rd, City",
    menu: [
      {
        name: "Pork Dumplings",
        category: "Appetizers",
        price: 200,
        img: "https://images.pexels.com/photos/7413153/pexels-photo-7413153.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Spring Rolls",
        category: "Appetizers",
        price: 160,
        img: "https://images.pexels.com/photos/3569706/pexels-photo-3569706.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Wonton Soup",
        category: "Soup",
        price: 125,
        img: "https://images.pexels.com/photos/6693237/pexels-photo-6693237.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Dim Sum Platter",
        category: "Dim Sum",
        price: 250,
        img: "https://images.pexels.com/photos/5409020/pexels-photo-5409020.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Beef Stir-Fry",
        category: "Main Course",
        price: 475,
        img: "https://images.pexels.com/photos/1234673/pexels-photo-1234673.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Chicken with Cashews",
        category: "Main Course",
        price: 500,
        img: "https://images.pexels.com/photos/1234512/pexels-photo-1234512.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Egg Fried Rice",
        category: "Sides",
        price: 310,
        img: "https://images.pexels.com/photos/8197469/pexels-photo-8197469.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Vegetable Lo Mein",
        category: "Sides",
        price: 170,
        img: "https://images.pexels.com/photos/3320215/pexels-photo-3320215.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Hot & Sour Soup",
        category: "Soup",
        price: 125,
        img: "https://images.pexels.com/photos/3222834/pexels-photo-3222834.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Sesame Chicken",
        category: "Main Course",
        price: 355,
        img: "https://images.pexels.com/photos/1746822/pexels-photo-1746822.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
    ],
  },
  {
    id: 15,
    name: "Grill and Chill",
    cuisine: "Grill",
    rating: 4.6,
    promoted: false,
    deliveryTime: "40-50 mins",
    image:
      "https://images.pexels.com/photos/1482803/pexels-photo-1482803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    address: "123 Chill St, City",
    menu: [
      {
        name: "Grilled Chicken",
        category: "Grilled",
        price: 355,
        img: "https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Steak",
        category: "Grilled",
        price: 555,
        img: "https://images.pexels.com/photos/1352264/pexels-photo-1352264.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "BBQ Sausage",
        category: "Grilled",
        price: 800,
        img: "https://images.pexels.com/photos/3162040/pexels-photo-3162040.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Grilled Veggies",
        category: "Sides",
        price: 600,
        img: "https://images.pexels.com/photos/3224804/pexels-photo-3224804.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Ribs",
        category: "Grilled",
        price: 500,
        img: "https://images.pexels.com/photos/3060777/pexels-photo-3060777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Grilled Shrimp",
        category: "Grilled",
        price: 950,
        img: "https://images.pexels.com/photos/3498046/pexels-photo-3498046.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Cheese Fries",
        category: "Sides",
        price: 250,
        img: "https://images.pexels.com/photos/2027457/pexels-photo-2027457.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Coleslaw",
        category: "Sides",
        price: 300,
        img: "https://images.pexels.com/photos/2088299/pexels-photo-2088299.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Onion Rings",
        category: "Sides",
        price: 275,
        img: "https://images.pexels.com/photos/1365892/pexels-photo-1365892.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Grilled Salmon",
        category: "Grilled",
        price: 375,
        img: "https://images.pexels.com/photos/1235641/pexels-photo-1235641.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
    ],
  },
  {
    id: 16,
    name: "Falafel Hut",
    cuisine: "Middle Eastern",
    rating: 4.4,
    promoted: true,
    deliveryTime: "20-30 mins",
    image:
      "https://images.pexels.com/photos/17650172/pexels-photo-17650172/free-photo-of-meal-with-spices-on-plate.jpeg?auto=compress&cs=tinysrgb&w=600",
    address: "456 Falafel St, City",
    menu: [
      {
        name: "Falafel Wrap",
        category: "Main Course",
        price: 800,
        img: "https://images.pexels.com/photos/5175621/pexels-photo-5175621.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Hummus",
        category: "Appetizer",
        price: 500,
        img: "https://images.pexels.com/photos/1618898/pexels-photo-1618898.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      },
      {
        name: "Baklava",
        category: "Dessert",
        price: 400,
        img: "https://images.pexels.com/photos/7393902/pexels-photo-7393902.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Shawarma",
        category: "Main Course",
        price: 200,
        img: "https://images.pexels.com/photos/3861477/pexels-photo-3861477.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Fattoush Salad",
        category: "Salad",
        price: 600,
        img: "https://images.pexels.com/photos/1128635/pexels-photo-1128635.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Tabbouleh",
        category: "Salad",
        price: 700,
        img: "https://images.pexels.com/photos/1593035/pexels-photo-1593035.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Falafel Platter",
        category: "Main Course",
        price: 500,
        img: "https://images.pexels.com/photos/6121798/pexels-photo-6121798.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Baba Ganoush",
        category: "Appetizer",
        price: 600,
        img: "https://images.pexels.com/photos/3489255/pexels-photo-3489255.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Stuffed Grape Leaves",
        category: "Appetizer",
        price: 500,
        img: "https://images.pexels.com/photos/1366876/pexels-photo-1366876.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
      {
        name: "Kunafa",
        category: "Dessert",
        price: 500,
        img: "https://images.pexels.com/photos/1792116/pexels-photo-1792116.jpeg?auto=compress&cs=tinysrgb&w=600",
      },
    ],
  },
];

export default restaurantData;
